# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calgayasf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(310, 570)
        Calculator.setStyleSheet("#Form{\n"
"    background:#aaffff;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:#ffaaff;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:30px;\n"
"    color:#202020;\n"
"}\n"
"QToolButton{\n"
"    background:#ffaaff;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:40px;\n"
"    color:white;\n"
"}\n"
"QLineEdit{\n"
"    background:#202020;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:120px;\n"
"    color:white;\n"
"}")
        self.output = QtWidgets.QLabel(Calculator)
        self.output.setGeometry(QtCore.QRect(10, 10, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        
        self.output.setFont(font)
        self.output.setFrameShape(QtWidgets.QFrame.Box)
        self.output.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output.setLineWidth(0)
        self.output.setMidLineWidth(1)
        self.output.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output.setObjectName("output")
        self.output.setStyleSheet("background-color: #ff00ff; color: white;")
  
        self.pushButton7 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("7"))
        self.pushButton7.setGeometry(QtCore.QRect(10, 170, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        
        self.pushButton8 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("8"))
        self.pushButton8.setGeometry(QtCore.QRect(80, 170, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton8.setFont(font)
        self.pushButton8.setObjectName("pushButton8")
        
        self.pushButton9 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("9"))
        self.pushButton9.setGeometry(QtCore.QRect(150, 170, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton9.setFont(font)
        self.pushButton9.setObjectName("pushButton9")
        
        self.pushButtondivide = QtWidgets.QPushButton(Calculator, clicked= lambda: self.function("/"))
        self.pushButtondivide.setGeometry(QtCore.QRect(240, 170, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtondivide.setFont(font)
        self.pushButtondivide.setObjectName("pushButtondivide")
        self.pushButtondivide.setStyleSheet("color: white;")
        
        self.pushButton4 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("4"))
        self.pushButton4.setGeometry(QtCore.QRect(10, 250, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton4.setFont(font)
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton1 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("1"))
        self.pushButton1.setGeometry(QtCore.QRect(10, 330, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButtoneq = QtWidgets.QPushButton(Calculator, clicked= lambda: self.math())
        self.pushButtoneq.setGeometry(QtCore.QRect(10, 410, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtoneq.setFont(font)
        self.pushButtoneq.setObjectName("pushButtoneq")
        self.pushButtonce = QtWidgets.QPushButton(Calculator, clicked= lambda: self.wtfisce())
        self.pushButtonce.setGeometry(QtCore.QRect(10, 490, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtonce.setFont(font)
        self.pushButtonce.setObjectName("pushButtonce")
        self.pushButtonce.setStyleSheet("color: #ff00ff;")
        
        self.pushButton5 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("5"))
        self.pushButton5.setGeometry(QtCore.QRect(80, 250, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton5.setFont(font)
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton2 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("2"))
        self.pushButton2.setGeometry(QtCore.QRect(80, 330, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton6 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("6"))
        self.pushButton6.setGeometry(QtCore.QRect(150, 250, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton6.setFont(font)
        self.pushButton6.setObjectName("pushButton6")
        
        self.pushButton3 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("3"))
        self.pushButton3.setGeometry(QtCore.QRect(150, 330, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        
        self.pushButton0 = QtWidgets.QPushButton(Calculator, clicked= lambda: self.press("0"))
        self.pushButton0.setGeometry(QtCore.QRect(80, 410, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButton0.setFont(font)
        self.pushButton0.setObjectName("pushButton0")
        
        self.pushButtondot = QtWidgets.QPushButton(Calculator, clicked= lambda: self.dot())
        self.pushButtondot.setGeometry(QtCore.QRect(150, 410, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtondot.setFont(font)
        self.pushButtondot.setObjectName("pushButtondot")
        
        self.pushButtonmultiply = QtWidgets.QPushButton(Calculator, clicked= lambda: self.function("*"))
        self.pushButtonmultiply.setGeometry(QtCore.QRect(240, 250, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtonmultiply.setFont(font)
        self.pushButtonmultiply.setObjectName("pushButtonmultiply")
        self.pushButtonmultiply.setStyleSheet("color: white;")
        
        self.pushButtonsub = QtWidgets.QPushButton(Calculator, clicked= lambda: self.function("-"))
        self.pushButtonsub.setGeometry(QtCore.QRect(240, 330, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtonsub.setFont(font)
        self.pushButtonsub.setObjectName("pushButtonsub")
        self.pushButtonsub.setStyleSheet("color: white;")
        self.pushButtonadd = QtWidgets.QPushButton(Calculator, clicked= lambda: self.function("+"))
        self.pushButtonadd.setGeometry(QtCore.QRect(240, 410, 61, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtonadd.setFont(font)
        self.pushButtonadd.setObjectName("pushButtonadd")
        self.pushButtonadd.setStyleSheet("color: white;")
        self.pushButtonc = QtWidgets.QPushButton(Calculator, clicked= lambda: self.resets())
        self.pushButtonc.setGeometry(QtCore.QRect(160, 490, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Arial,Helvetica,sans-serif")
        font.setPointSize(-1)
        self.pushButtonc.setFont(font)
        self.pushButtonc.setObjectName("pushButtonc")
        self.pushButtonc.setStyleSheet("color: #ff00ff;")
        
        self.output_2 = QtWidgets.QLabel(Calculator)
        self.output_2.setGeometry(QtCore.QRect(10, 60, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.output_2.setFont(font)
        self.output_2.setFrameShape(QtWidgets.QFrame.Box)
        self.output_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.output_2.setLineWidth(1)
        self.output_2.setMidLineWidth(2)
        self.output_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.output_2.setObjectName("output_2")
        self.output_2.setStyleSheet("color: #ff00ff;")
        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def dot(self):
        #this is to prevent double dot  in a value
        screen = self.output_2.text()
        if "." in screen:
            pass
        else:
            self.output_2.setText(f'{screen}.')

    def press(self, pressed):
        #try adding limits to number
        screem = self.output_2.text()
        screem = str(screem)
        if len(screem) <= 12:
        #number before pressing function or equal
            if self.output_2.text() == "0":
                self.output_2.setText(pressed)

            else:
                self.output_2.setText(f'{self.output_2.text()}{pressed}')

    def resets(self):
        # C
        self.output.setText("0")
        self.output_2.setText("0")

    def function(self,pressed):
        #number goes to output1 then output2 becomes 0, waiting for more inputs
        if self.output.text() == "0":
            self.output.setText(f'{self.output_2.text()}{pressed}')
            self.output_2.setText('0')
        else:
            self.output.setText(f'{self.output.text()}{self.output_2.text()}{pressed}')
            self.output_2.setText('0')

    def math(self):
        #prevent stupid people from pressing number then equal without any + - * /
        if self.output.text() == "0":
            screen = self.output_2.text()
        else:
            self.output.setText(f'{self.output.text()}{self.output_2.text()}')
            screen = self.output.text()
        try:
            answer = eval(screen)
            if len(str(answer)) <= 13:
                self.output_2.setText(str(answer))
                self.output.setText("0")
            else:
                #This is to change output if it exceeds the given area of box
                count = 13
                textanswer = str(answer)
                numanswer = answer
                #one where the output is float
                if "." in textanswer:
                    while len(textanswer) > 13 and count > 0:
                        numanswer = round(numanswer, count)
                        textanswer = str(numanswer)
                        count -= 1
                    self.output_2.setText(textanswer)
                    self.output.setText("0")
                    #another one where if already round the float but still exceeds the given space
                    if len(textanswer) > 13:
                        finalanswer = textanswer[0]+"."+textanswer[1]+"e"+str(len(textanswer)-3)
                        self.output_2.setText(finalanswer)
                #one where the output is integer
                else:
                    jumnuan = len(textanswer)
                    finalanswer = textanswer[0]+"."+textanswer[1]+"e"+str(jumnuan-1)
                    self.output_2.setText(str(finalanswer))
                    self.output.setText("0")
        except:
            self.output_2.setText("Error")
            self.output.setText("0")


    def wtfisce(self):
        #reset only the output2 value
        self.output_2.setText("0")

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.output.setText(_translate("Calculator", "0"))
        self.pushButton7.setText(_translate("Calculator", "7"))
        self.pushButton8.setText(_translate("Calculator", "8"))
        self.pushButton9.setText(_translate("Calculator", "9"))
        self.pushButtondivide.setText(_translate("Calculator", "/"))
        self.pushButton4.setText(_translate("Calculator", "4"))
        self.pushButton1.setText(_translate("Calculator", "1"))
        self.pushButtoneq.setText(_translate("Calculator", "="))
        self.pushButtonce.setText(_translate("Calculator", "CE"))
        self.pushButton5.setText(_translate("Calculator", "5"))
        self.pushButton2.setText(_translate("Calculator", "2"))
        self.pushButton6.setText(_translate("Calculator", "6"))
        self.pushButton3.setText(_translate("Calculator", "3"))
        self.pushButton0.setText(_translate("Calculator", "0"))
        self.pushButtondot.setText(_translate("Calculator", "."))
        self.pushButtonmultiply.setText(_translate("Calculator", "*"))
        self.pushButtonsub.setText(_translate("Calculator", "-"))
        self.pushButtonadd.setText(_translate("Calculator", "+"))
        self.pushButtonc.setText(_translate("Calculator", "C"))
        self.output_2.setText(_translate("Calculator", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QWidget()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())